"""Add to User new fields - active and superuser

Revision ID: 046efa9cef42
Revises: cdfeda1ebd25
Create Date: 2024-05-20 20:26:42.018288

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "046efa9cef42"
down_revision: Union[str, None] = "cdfeda1ebd25"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("superuser", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "superuser")
    # ### end Alembic commands ###
